language: python
sudo: required

services:
  - docker

python:
  - 3.5
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install 'coverage>4.0,<4.4'
  - pip install codecov
  
script:
  # Shared
  - coverage run -m unittest -v tests
  
after_success:
  - codecov
  - "pycodestyle aims"

before_install:
  - docker build -t denzuko/aims .
  - docker stack init
  - docker stack deploy -c docker-compose.yml aims
  - curl localhost:8080

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push denzuko/aims:latest
  on:
    branch: master
