---
version: '3.7'

x-labels: &metadata
  org.label-schema.vendor: "denzuko"
  org.label-schema.url: "https://dwightaspencer.com"
  org.label-schema.name: "aims"
  org.label-schema.description: "ansible inventory management system"
  org.label-schema.version: 1.0.0
  org.label-schema.vcs-url: "https://github.com/denzuko/AIMS"
  org.label-schema.vcs-ref: "master"
  org.label-schema.docker.schema-version: "1.0"
  com.dwightaspencer.role: "cmdb"
  com.dwightaspencer.owner: "INT-01"

services:
  api:
    image: 'denzuko/aims:latest'
    ports:
      - '8080/tcp'
    depends_on:
      - redis
      - mongodb
    deploy:
     replicas: 3
    labels: <<: *metadata
    networks:
      - default
  mongo:
    image: 'mongo:latest'
    volumes:
      - mongodata:/data/db/mongo
    labels: <<: *metadata
    networks:
      default:
        aliasas:
          - 'mongodb'
          - 'redis'
      ports:
        - "27017"
        
  redis:
    image: 'redis:latest'
    volumes:
      - redisdata:/data/db/redis
    ports:
      - 6379/tcp
    labels: <<: *metadata
    networks:
      default:
        aliasas:
          - 'redis'

volumes:
  mongodata: {}
  redisdata: {}
  
networks:
  default: {}
...
# vim: set sw=2 sts=2 ts=2 et ai cin numbers list :
